### ISSUE TITLE
Handle decryption failure in some good way

### ISSUE THREAD

**Issue by photm5** [shak-mar/weecrypt#4]
Currently, when decrypting a message fails, for example when you don't enter your password in time, it will just replace the message with `Error: Decryption failed.`. You are not able to decrypt the message afterwards.

We should change this so that failed messages are stored in an internal buffer. A user could then invoke a command (like `/weecrypt_pop` or sth like that) that triggers a decryption of all failed messages. (or of all messages that weren't tried with `/weecrypt_pop` yet)

**Comment by photm5** [comment]
As of 5f5888a, the ciphertext is shown, instead of `Error: Decryption failed.`. This allows you to decrypt the message by hand.

**Comment by froozen** [comment]
Seems like a pretty good approach.
